import type { EngineEvent } from "./events.js";
import { createInitialState, reduce, type EngineState } from "./reducer.js";
import type { ScenarioDef } from "./scenario.js";

/**
 * AAR model — generated by deterministic replay of the event log, never by
 * snapshotting mutable state (vetcrew-sim-architecture doctrine). The AAR
 * viewer scrubs this model; scores link into it via event seqs.
 */

export interface AarTimelineEntry {
  readonly seq: number;
  readonly timeMs: number;
  readonly type: EngineEvent["type"];
  readonly role?: string;
  readonly actorId?: string;
  readonly action?: string;
  readonly injection?: string;
  readonly phase?: string;
}

export interface AarVitalsSample {
  readonly timeMs: number;
  readonly vitals: Readonly<Record<string, number>>;
}

export interface AarModel {
  readonly durationMs: number;
  readonly timeline: readonly AarTimelineEntry[];
  readonly vitalsSeries: readonly AarVitalsSample[];
  readonly finalState: EngineState;
}

function sample(state: EngineState): AarVitalsSample {
  const vitals: Record<string, number> = {};
  for (const [name, vital] of Object.entries(state.vitals)) {
    vitals[name] = vital.value;
  }
  return { timeMs: state.timeMs, vitals };
}

export function buildAar(
  seed: number,
  events: readonly EngineEvent[],
  scenario: ScenarioDef,
): AarModel {
  let state = createInitialState(seed, scenario);
  const timeline: AarTimelineEntry[] = [];
  const vitalsSeries: AarVitalsSample[] = [sample(state)];

  for (const event of events) {
    state = reduce(state, event);
    switch (event.type) {
      case "tick":
        timeline.push({ seq: event.seq, timeMs: state.timeMs, type: event.type });
        vitalsSeries.push(sample(state));
        break;
      case "action":
        timeline.push({
          seq: event.seq,
          timeMs: state.timeMs,
          type: event.type,
          role: event.role,
          actorId: event.actorId,
          action: event.action,
        });
        break;
      case "injection":
        timeline.push({
          seq: event.seq,
          timeMs: state.timeMs,
          type: event.type,
          injection: event.injection,
        });
        break;
      case "phase_change":
        timeline.push({
          seq: event.seq,
          timeMs: state.timeMs,
          type: event.type,
          phase: event.phase,
        });
        break;
      default: {
        const exhaustive: never = event;
        throw new Error(`Unhandled event: ${JSON.stringify(exhaustive)}`);
      }
    }
  }

  return { durationMs: state.timeMs, timeline, vitalsSeries, finalState: state };
}
