import { describe, expect, test } from "vitest";

import { buildAar, type EngineEvent, type ScenarioDef } from "../src/index.js";

/** AAR is generated by deterministic replay of the log — never stored state. */

const SCENARIO: ScenarioDef = {
  slug: "aar-test",
  version: "0.0.1",
  vitals: {
    spo2: { initial: 95, target: 80, ratePerSec: 0.5, jitter: 0 },
  },
  triggers: [
    {
      id: "oxygen",
      on: { kind: "action", action: "oxygen_on" },
      effects: [{ vital: "spo2", target: 97, ratePerSec: 1 }],
    },
  ],
};

const EVENTS: EngineEvent[] = [
  { seq: 1, type: "phase_change", phase: "briefing" },
  { seq: 2, type: "phase_change", phase: "running" },
  { seq: 3, type: "tick", dtMs: 10_000 },
  { seq: 4, type: "action", role: "technician", actorId: "t1", action: "oxygen_on" },
  { seq: 5, type: "tick", dtMs: 10_000 },
  { seq: 6, type: "phase_change", phase: "debrief" },
];

describe("AAR builder", () => {
  test("timeline attributes every event with its session time", () => {
    const aar = buildAar(7, EVENTS, SCENARIO);
    expect(aar.timeline).toHaveLength(6);
    const action = aar.timeline.find((entry) => entry.seq === 4);
    expect(action?.timeMs).toBe(10_000);
    expect(action?.role).toBe("technician");
    const lastTick = aar.timeline.find((entry) => entry.seq === 5);
    expect(lastTick?.timeMs).toBe(20_000);
  });

  test("vitals series samples state after every tick", () => {
    const aar = buildAar(7, EVENTS, SCENARIO);
    expect(aar.vitalsSeries).toHaveLength(3); // initial + 2 ticks
    expect(aar.vitalsSeries[0]?.vitals["spo2"]).toBe(95);
    expect(aar.vitalsSeries[1]?.vitals["spo2"]).toBeCloseTo(90, 5); // fell 10s * 0.5
    expect(aar.vitalsSeries[2]?.vitals["spo2"]).toBeCloseTo(97, 5); // recovered, clamped at 97
  });

  test("duration and final phase come from the replay", () => {
    const aar = buildAar(7, EVENTS, SCENARIO);
    expect(aar.durationMs).toBe(20_000);
    expect(aar.finalState.phase).toBe("debrief");
  });

  test("AAR is deterministic: same log => byte-identical model", () => {
    const a = buildAar(7, EVENTS, SCENARIO);
    const b = buildAar(7, EVENTS, SCENARIO);
    expect(JSON.stringify(a)).toBe(JSON.stringify(b));
  });
});
